𝗖𝗼𝘂𝗻𝘁 𝗼𝗿 𝗳𝗿𝗲𝗾𝘂𝗲𝗻𝗰𝘆 𝗲𝗻𝗰𝗼𝗱𝗶𝗻𝗴


High Cardinality

Another way to refer to variables that have a multitude of categories, is to call them variables with high cardinality.

If we have categorical variables containing many multiple labels or high cardinality,then by using one hot encoding, we will expand the feature space dramatically.

One approach that is heavily used in Kaggle competitions, is to replace each label of the categorical variable by the count, this is the amount of times each label appears in the dataset. Or the frequency, this is the percentage of observations within that category. The 2 are equivalent.

Let's see how this works:

In [61]:
import pandas as pd 
import numpy as np 

df=pd.read_csv('Mercedesbenz.csv', usecols=['X1','X2'])
df.head()

  X1  X2
0  v  at
1  t  av
2  w   n
3  t   n
4  v   n

In [62]:
df.shape

(4209, 2)

𝗢𝗻𝗲 𝗵𝗼𝘁 𝗘𝗻𝗰𝗼𝗱𝗶𝗻𝗴

In [63]:
pd.get_dummies(df).shape

(4209, 71)

In [64]:
len(df['X1'].unique())

27

In [65]:
len(df['X2'].unique())

44

In [66]:
# Let's have a look at how many Labels

for col in df.columns:
    print(col, ':' , len(df[col].unique()), 'labels')

X1 : 27 labels
X2 : 44 labels

In [67]:
df.X2.unique()

array(['at', 'av', 'n', 'e', 'as', 'aq', 'r', 'ai', 'ak', 'm', 'a', 'k',
       'ae', 's', 'f', 'd', 'ag', 'ay', 'ac', 'ap', 'g', 'i', 'aw', 'y',
       'b', 'ao', 'al', 'h', 'x', 'au', 't', 'an', 'z', 'ah', 'p', 'am',
       'j', 'q', 'af', 'l', 'aa', 'c', 'o', 'ar'], dtype=object)

In [68]:
# Let's obtain the counts for each one of the labels in variable X2
# Let's capture this in a dictionary that we can use to re-map the labels

# And now Let's replace each Label in X2 by its count

# first we make a dictionary that maps each label to the counts
df_frequency_map=df.X2.value_counts().to_dict()

In [69]:
df_frequency_map

{'as': 1659,
 'ae': 496,
 'ai': 415,
 'm': 367,
 'ak': 265,
 'r': 153,
 'n': 137,
 's': 94,
 'f': 87,
 'e': 81,
 'aq': 63,
 'ay': 54,
 'a': 47,
 't': 29,
 'k': 25,
 'i': 25,
 'b': 21,
 'ao': 20,
 'z': 19,
 'ag': 19,
 'd': 18,
 'ac': 13,
 'g': 12,
 'ap': 11,
 'y': 11,
 'x': 10,
 'aw': 8,
 'at': 6,
 'h': 6,
 'q': 5,
 'al': 5,
 'an': 5,
 'av': 4,
 'p': 4,
 'ah': 4,
 'au': 3,
 'am': 1,
 'j': 1,
 'af': 1,
 'l': 1,
 'aa': 1,
 'c': 1,
 'o': 1,
 'ar': 1}

In [70]:
df.head(100)

    X1  X2
0    v  at
1    t  av
2    w   n
3    t   n
4    v   n
..  ..  ..
95   b   m
96   l  as
97  aa  as
98   b   m
99   s   m

[100 rows x 2 columns]

In [ ]:
df.X2 = df.X2.map(df_frequency_map)

df.head()

  X1   X2
0  v    6
1  t    4
2  w  137
3  t  137
4  v  137

:

There are some advantages and disadvantages that we will discuss now

Advantages
1. It is very simple to implement
2. Does not increase the feature dimensional space




Disadvantages
1. If some of the labels have the same count, then they will be replaced with the same count and they will loose some valuable information.
2. 2 Adds somewhat arbitrary numbers, and therefore weights to the different labels, that may not be related to their predictive power

Follow this thread in Kaggle for more information: https://www.kaggle.com/general/16927